# This command sets the base image to python 3.9
FROM python:3.9

#Copies the contents of the published app to the container's /app directory
COPY requirements.txt /tmp/

RUN pip install --no-cache-dir --upgrade pip && \
    pip install --requirement /tmp/requirements.txt

copy ./src/writer_json.py /src/writer_json.py

ENTRYPOINT ["python","./src/writer_json.py"]